# Generated by Django 4.2.16 on 2024-10-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dateBegin', models.CharField(max_length=100)),
                ('dateEnd', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
