# Generated by Django 4.2.16 on 2024-10-25 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_page_category_alter_page_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='index.category'),
        ),
    ]
