# Generated by Django 4.2.16 on 2024-10-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_page_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
    ]
