# Generated by Django 4.2.16 on 2024-10-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_category_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='journal',
        ),
        migrations.AddField(
            model_name='category',
            name='journal',
            field=models.ManyToManyField(null=True, to='index.journal'),
        ),
    ]
