# Generated by Django 4.2.16 on 2024-10-25 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_remove_category_journal_category_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='journal',
        ),
        migrations.AddField(
            model_name='category',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.journal'),
        ),
    ]
